language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mamun18/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mamun18/docker-react npm run test